trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'AzureServiceConnection' # Replace with your service connection name
  appName: 'app-iw5-2024-team-xpopov10-api' # Replace with your Azure App Service name
  environmentName: 'production'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build Job
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '6.0.x' # Use the version appropriate for your app

          - script: dotnet build --configuration Release
            displayName: 'Build Solution'

          - task: DotNetCoreCLI@2
            displayName: 'Publish Artifact'
            inputs:
              command: 'publish'
              publishWebProjects: true
              arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: true

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: drop

  - stage: Deploy
    displayName: Deploy Stage
    dependsOn: Build
    jobs:
      - deployment: DeployWeb
        displayName: Deploy Job
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appType: webApp
                    appName: $(appName)
                    package: $(Pipeline.Workspace)/drop/**/*.zip
